import type { CategoryItem, ServiceItem, TemplateFormat, TemplateItem } from '../types'

const FORMATS: TemplateFormat[] = ['Canva', 'PSD', 'AI', 'PDF', 'FIG']

interface CategorySeed {
  id: string
  name: string
  description: string
  galleryUrl: string
  templateNames: string[]
}

const CATEGORY_SEEDS: CategorySeed[] = [
  {
    id: 'posters',
    name: 'Posters',
    description: 'Bold poster designs for promotions, events and announcements.',
    galleryUrl: 'https://www.google.com/search?q=poster+templates',
    templateNames: [
      'Summer Sale Poster',
      'Music Night Poster',
      'Product Launch Poster',
      'Film Festival Poster',
      'Concert Night Poster',
      'Black Friday Poster',
      'Fitness Challenge Poster',
      'Art Exhibition Poster',
      'Food Festival Poster',
      'Travel Sale Poster',
      'Webinar Promo Poster',
      'Grand Opening Poster',
      'Charity Run Poster',
      'New Year Party Poster',
      'Book Fair Poster',
      'Tech Conference Poster',
      'Flash Sale Poster',
      'Yoga Retreat Poster',
      'Community Event Poster',
      'Sports Day Poster',
      'Fashion Show Poster',
      'Coffee Shop Poster',
      'Holiday Market Poster',
      'Workshop Poster',
    ],
  },
  {
    id: 'banners',
    name: 'Banners',
    description: 'High-impact banner layouts for digital and print campaigns.',
    galleryUrl: 'https://www.google.com/search?q=banner+templates',
    templateNames: [
      'Website Hero Banner',
      'Festival Offer Banner',
      'Social Media Banner',
      'YouTube Channel Banner',
      'Email Header Banner',
      'Sale Banner',
      'Event Banner',
      'Newsletter Banner',
      'Twitter Header Banner',
      'Facebook Cover Banner',
      'Discount Banner',
      'Launch Banner',
      'Holiday Banner',
      'Countdown Banner',
      'Webinar Banner',
      'Giveaway Banner',
      'Podcast Banner',
      'Black Friday Banner',
      'App Promo Banner',
      'Store Banner',
      'Announcement Banner',
      'Seasonal Banner',
      'Membership Banner',
      'Thank You Banner',
    ],
  },
  {
    id: 'menu-cards',
    name: 'Menu Cards',
    description: 'Polished menu cards for restaurants, cafes and special events.',
    galleryUrl: 'https://www.google.com/search?q=menu+card+templates',
    templateNames: [
      'Cafe Menu Card',
      'Restaurant Specials Menu',
      'Dessert Menu Card',
      'Wedding Menu Card',
      'Bar Menu Card',
      'Breakfast Menu Card',
      'Christmas Menu Card',
      'Cocktail Menu Card',
      'Takeaway Menu Card',
      'Fine Dining Menu',
      'Brunch Menu Card',
      'Kids Menu Card',
      'Wine List Menu',
      'Birthday Party Menu',
      'BBQ Menu Card',
      'Healthy Bowl Menu',
      'Coffee Shop Menu',
      'Festival Food Menu',
      'Buffet Menu Card',
      'Sushi Menu Card',
      'Bakery Menu Card',
      'Ice Cream Menu',
      'Thanksgiving Menu',
      'Tapas Menu Card',
    ],
  },
  {
    id: 'invitations',
    name: 'Invitations',
    description: 'Custom invitations for weddings, parties and celebrations.',
    galleryUrl: 'https://www.google.com/search?q=invitation+templates',
    templateNames: [
      'Wedding Invitation',
      'Birthday Party Invite',
      'Housewarming Invite',
      'Baby Shower Invitation',
      'Engagement Party Invite',
      'Graduation Invitation',
      'Anniversary Invitation',
      'Bridal Shower Invite',
      'Retirement Party Invite',
      'New Year Eve Invite',
      'Dinner Party Invitation',
      'Christening Invitation',
      'Bachelor Party Invite',
      'Gender Reveal Invite',
      'Farewell Party Invitation',
      'Festival Invitation',
      'Gala Invitation',
      'Reunion Invite',
      'BBQ Invitation',
      'Tea Party Invite',
      'Corporate Event Invite',
      'Holiday Party Invitation',
      'Save The Date Card',
      'Valentine Invite',
    ],
  },
  {
    id: 'magazines',
    name: 'Magazines',
    description: 'Editorial magazine layouts with clean typography and visual flow.',
    galleryUrl: 'https://www.google.com/search?q=magazine+templates',
    templateNames: [
      'Fashion Lookbook Spread',
      'Business Magazine Cover',
      'Travel Feature Layout',
      'Food Magazine Spread',
      'Tech Magazine Cover',
      'Lifestyle Magazine Layout',
      'Interior Design Feature',
      'Sports Magazine Cover',
      'Music Magazine Spread',
      'Health & Wellness Layout',
      'News Magazine Cover',
      'Beauty Editorial Spread',
      'Architecture Feature',
      'Automobile Magazine Layout',
      'Culture Magazine Cover',
      'Fitness Feature Spread',
      'Wedding Magazine Layout',
      'Finance Magazine Cover',
      'Art Magazine Spread',
      'Nature Feature Layout',
      'Recipe Magazine Spread',
      'Fashion Week Cover',
      'Photography Feature',
      'Year In Review Layout',
    ],
  },
  {
    id: 'resumes',
    name: 'Resumes',
    description: 'Professional resume designs that present skills clearly.',
    galleryUrl: 'https://www.google.com/search?q=resume+templates',
    templateNames: [
      'Creative Designer Resume',
      'Corporate Resume',
      'Fresher Resume',
      'Software Engineer Resume',
      'Marketing Resume',
      'Nursing Resume',
      'Teacher Resume',
      'Graphic Designer Resume',
      'Finance Resume',
      'Data Analyst Resume',
      'MBA Resume',
      'Hospitality Resume',
      'Sales Resume',
      'Legal Resume',
      'Architect Resume',
      'Photographer Resume',
      'Chef Resume',
      'UX Designer Resume',
      'Doctor Resume',
      'Student Resume',
      'Executive Resume',
      'Customer Service Resume',
      'Engineer Resume',
      'Freelancer Resume',
    ],
  },
  {
    id: 'certificates',
    name: 'Certificates',
    description: 'Elegant certificate templates for awards, courses and recognition.',
    galleryUrl: 'https://www.google.com/search?q=certificate+templates',
    templateNames: [
      'Course Completion Certificate',
      'Appreciation Certificate',
      'Achievement Award Certificate',
      'Participation Certificate',
      'Excellence Award Certificate',
      'Diploma Certificate',
      'Merit Certificate',
      'Training Completion Certificate',
      'Honorary Certificate',
      'Employee Of The Month',
      'Recognition Certificate',
      'Graduation Certificate',
      'Winner Certificate',
      'Attendance Certificate',
      'Leadership Award',
      'Sports Achievement Certificate',
      'Volunteer Certificate',
      'Seminar Certificate',
      'Scholarship Certificate',
      'Best Performer Award',
      'Workshop Certificate',
      'Certification Of Achievement',
      'Star Performer Certificate',
      'Commendation Certificate',
    ],
  },
  {
    id: 'backgrounds',
    name: 'Backgrounds',
    description: 'Versatile image backgrounds for designs, devices and social posts.',
    galleryUrl: 'https://www.google.com/search?q=background+templates',
    templateNames: [
      'Abstract Gradient Background',
      'Minimal Solid Background',
      'Geometric Pattern Background',
      'Floral Background',
      'Dark Mode Background',
      'Pastel Background',
      'Watercolor Background',
      'Tech Grid Background',
      'Boho Background',
      'Marble Texture Background',
      'Neon Background',
      'Vintage Background',
      'Nature Landscape Background',
      'Blur Bokeh Background',
      'Stripes Background',
      'Polka Dot Background',
      'Cloud Background',
      'Galaxy Space Background',
      'Gradient Mesh Background',
      'Concrete Texture Background',
      'Tropical Background',
      'Cartoon Background',
      'Holiday Background',
      'Anime Background',
    ],
  },
]

const buildTemplates = (categoryId: string, names: string[]): TemplateItem[] =>
  names.map((title, index) => ({
    id: `${categoryId}-${index + 1}`,
    title,
    description: `Fully customizable ${title.toLowerCase()} with editable text and brand colors.`,
    format: FORMATS[index % FORMATS.length],
  }))

export const CATEGORIES: CategoryItem[] = CATEGORY_SEEDS.map((seed) => ({
  id: seed.id,
  name: seed.name,
  description: seed.description,
  galleryUrl: seed.galleryUrl,
  templates: buildTemplates(seed.id, seed.templateNames),
}))

export const SERVICES: ServiceItem[] = [
  { id: 'shipping', title: 'Fast Shipping', description: 'Express delivery on every order, tracked door to door.' },
  { id: 'payment', title: 'Secure Payment', description: 'Encrypted checkout with every major payment method.' },
  { id: 'support', title: '24/7 Support', description: 'Our team is always on, ready to help around the clock.' },
  { id: 'returns', title: 'Easy Returns', description: 'Hassle-free returns within 30 days, no questions asked.' },
]

export const SOCIAL_LINKS = {
  facebook: 'https://facebook.com',
  twitter: 'https://twitter.com',
  youtube: 'https://youtube.com',
}
